### ISSUE TITLE
是否可以支持GPU加速运算

### ISSUE THREAD

**Issue by zhuangdx** [oldj/pyheatmap#10]
PIL支持GPU，热力图渲染可以利用GPU进行加速吗。

**Comment by yutao007** [comment]
同问，发现这个包在渲染挺好的。但是就是很吃内存，耗时很多。不知道是否有高手优化一下

**Comment by zhuangdx** [comment]
用cpython编译了渲染部分，速度飞起

**Comment by y1h6b** [comment]
请问下如何用cpython实现呢？能否给个教程😘
