### ISSUE TITLE
关于float类型data

### ISSUE THREAD

**Issue by lan2720** [oldj/pyheatmap#5]
hi，现在有一个x,y均为float类型的二维data set，
根据您的code
 def __heat(self, heat_data, x, y, n, template):
        u""""""

```
    l = len(heat_data)
    width = self.width
    p = width * y + x

    for ip, iv in template:
        p2 = p + ip
        if 0 <= p2 < l:
            heat_data[p2] += iv * n
```

由于是float类型， heat_data[p2]报错list indices must be integer
我尝试修改源码，但并不太明白其中原理部分，有没有办法能支持float类型数据绘制heatmap？

**Comment by oldj** [comment]
你能先将传入的数据取整么？

这边其实是在一个长度为 width * height 的数组里记录下图片每一个像素的热度值，再转为图片。能操作的最小单位是像素，所以传入的 x、y 坐标都应该是整数，小数超过绘制精度了，传入前取整即可。

**Comment by lan2720** [comment]
xy是经纬度坐标值，取整的话一度经纬度就能相差一百多公里偏差太大了。
不过还是谢谢啦！

在 2016年1月20日 上午11:20，oldj <notifications@github.com>写道：
