### ISSUE TITLE
能否支持自定义的背景图

### ISSUE THREAD

**Issue by matrixlibing** [oldj/pyheatmap#8]
是否可以在一个图片基础上画热区图或点击图？

**Comment by oldj** [comment]
可以，传入一个 `base` 参数，值为背景图的路径即可。

比如：

```python
hm.heatmap(save_as="heat.png", base="/var/tmp/test_base.png")
```

参见[这里](https://github.com/oldj/pyheatmap/blob/master/examples/test.py#L50)。

**Comment by ZoomQuiet** [comment]
DONE as good! 达成/归档/交付ed

确认, 已经用上了, 忘记了关闭 Issue

confirmed, working , close issue now

and happy new year
